-- Content-based routing table for the Connector Bus (SOA-Architecture.md
-- §3.3) — GENERATED from connectors/catalogue.json; regenerate rather than
-- hand-edit. The bus loads catalogue.json directly at startup; this table
-- is the durable mirror for audit joins and Beta-phase routing.
CREATE SCHEMA IF NOT EXISTS connectors;

DROP TABLE IF EXISTS connectors.audit_log;
DROP TABLE IF EXISTS connectors.registry;

CREATE TABLE connectors.registry (
    name TEXT PRIMARY KEY,
    category TEXT NOT NULL CHECK (category IN ('enterprise', 'productivity', 'devtools', 'aiplatform', 'data', 'messaging', 'industrial', 'cloud', 'government', 'education')),
    protocols TEXT NOT NULL,
    ai_risk_class TEXT NOT NULL CHECK (ai_risk_class IN ('AIA-R0', 'AIA-R1', 'AIA-R2', 'AIA-R3', 'AIA-R4')),
    min_trust_score INT NOT NULL DEFAULT 40,
    maturity TEXT NOT NULL DEFAULT 'stub' CHECK (maturity IN ('specialized', 'stub')),
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE connectors.audit_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    agent_id UUID NOT NULL,
    connector_name TEXT NOT NULL REFERENCES connectors.registry(name),
    outcome TEXT NOT NULL CHECK (outcome IN ('invoked', 'denied', 'failed')),
    reason TEXT,
    trust_score_at_call_time INT,
    created_at TIMESTAMPTZ DEFAULT now()
);

INSERT INTO connectors.registry (name, category, protocols, ai_risk_class, min_trust_score, maturity) VALUES
    ('sap', 'enterprise', 'SOAP,REST', 'AIA-R2', 60, 'stub'),
    ('salesforce', 'enterprise', 'SOAP,REST', 'AIA-R1', 50, 'specialized'),
    ('dynamics365', 'enterprise', 'REST', 'AIA-R2', 60, 'stub'),
    ('oracle-erp', 'enterprise', 'SOAP,REST', 'AIA-R2', 60, 'stub'),
    ('workday', 'enterprise', 'SOAP,REST', 'AIA-R2', 60, 'stub'),
    ('servicenow', 'enterprise', 'REST', 'AIA-R1', 50, 'stub'),
    ('bamboohr', 'enterprise', 'REST', 'AIA-R2', 60, 'stub'),
    ('successfactors', 'enterprise', 'REST', 'AIA-R2', 60, 'stub'),
    ('xero', 'enterprise', 'REST', 'AIA-R2', 60, 'stub'),
    ('quickbooks', 'enterprise', 'REST', 'AIA-R2', 60, 'stub'),
    ('netsuite', 'enterprise', 'SOAP,REST', 'AIA-R2', 60, 'stub'),
    ('hubspot', 'enterprise', 'REST', 'AIA-R1', 50, 'stub'),
    ('sage', 'enterprise', 'REST', 'AIA-R2', 60, 'stub'),
    ('zoho-crm', 'enterprise', 'REST', 'AIA-R1', 50, 'stub'),
    ('google-workspace', 'productivity', 'REST', 'AIA-R1', 50, 'stub'),
    ('microsoft365', 'productivity', 'REST', 'AIA-R1', 50, 'stub'),
    ('slack', 'productivity', 'REST', 'AIA-R0', 40, 'specialized'),
    ('teams', 'productivity', 'REST', 'AIA-R0', 40, 'stub'),
    ('zoom', 'productivity', 'REST', 'AIA-R0', 40, 'stub'),
    ('notion', 'productivity', 'REST', 'AIA-R0', 40, 'stub'),
    ('confluence', 'productivity', 'REST', 'AIA-R0', 40, 'stub'),
    ('trello', 'productivity', 'REST', 'AIA-R0', 40, 'stub'),
    ('asana', 'productivity', 'REST', 'AIA-R0', 40, 'stub'),
    ('monday', 'productivity', 'REST,GraphQL', 'AIA-R0', 40, 'stub'),
    ('dropbox', 'productivity', 'REST', 'AIA-R1', 50, 'stub'),
    ('github', 'devtools', 'REST,GraphQL', 'AIA-R0', 40, 'specialized'),
    ('gitlab', 'devtools', 'REST,GraphQL', 'AIA-R0', 40, 'stub'),
    ('jira', 'devtools', 'REST', 'AIA-R0', 40, 'stub'),
    ('azure-devops', 'devtools', 'REST', 'AIA-R0', 40, 'stub'),
    ('bitbucket', 'devtools', 'REST', 'AIA-R0', 40, 'stub'),
    ('jenkins', 'devtools', 'REST', 'AIA-R1', 50, 'stub'),
    ('circleci', 'devtools', 'REST', 'AIA-R1', 50, 'stub'),
    ('sonarqube', 'devtools', 'REST', 'AIA-R0', 40, 'stub'),
    ('artifactory', 'devtools', 'REST', 'AIA-R1', 50, 'stub'),
    ('dockerhub', 'devtools', 'REST', 'AIA-R0', 40, 'stub'),
    ('terraform-cloud', 'devtools', 'REST', 'AIA-R1', 50, 'stub'),
    ('ml', 'aiplatform', 'REST', 'AIA-R1', 40, 'specialized'),
    ('vllm', 'aiplatform', 'REST', 'AIA-R1', 40, 'stub'),
    ('llamacpp', 'aiplatform', 'REST', 'AIA-R1', 40, 'stub'),
    ('lmstudio', 'aiplatform', 'REST', 'AIA-R1', 40, 'stub'),
    ('openai', 'aiplatform', 'REST', 'AIA-R1', 40, 'stub'),
    ('anthropic', 'aiplatform', 'REST', 'AIA-R1', 40, 'stub'),
    ('gemini', 'aiplatform', 'REST', 'AIA-R1', 40, 'stub'),
    ('mistral', 'aiplatform', 'REST', 'AIA-R1', 40, 'stub'),
    ('cohere', 'aiplatform', 'REST', 'AIA-R1', 40, 'stub'),
    ('huggingface', 'aiplatform', 'REST', 'AIA-R1', 40, 'stub'),
    ('bedrock', 'aiplatform', 'REST', 'AIA-R1', 40, 'stub'),
    ('azure-openai', 'aiplatform', 'REST', 'AIA-R1', 40, 'stub'),
    ('vertex-ai', 'aiplatform', 'REST', 'AIA-R1', 40, 'stub'),
    ('deepseek', 'aiplatform', 'REST', 'AIA-R1', 40, 'stub'),
    ('postgresql', 'data', 'SQL', 'AIA-R1', 50, 'stub'),
    ('mysql', 'data', 'SQL', 'AIA-R1', 50, 'stub'),
    ('sqlserver', 'data', 'SQL', 'AIA-R1', 50, 'stub'),
    ('oracle-db', 'data', 'SQL', 'AIA-R1', 50, 'stub'),
    ('mongodb', 'data', 'Wire', 'AIA-R1', 50, 'stub'),
    ('cassandra', 'data', 'CQL', 'AIA-R1', 50, 'stub'),
    ('dynamodb', 'data', 'REST', 'AIA-R1', 50, 'stub'),
    ('redis', 'data', 'RESP', 'AIA-R0', 40, 'stub'),
    ('memcached', 'data', 'Memcache', 'AIA-R0', 40, 'stub'),
    ('pgvector', 'data', 'SQL', 'AIA-R1', 50, 'stub'),
    ('pinecone', 'data', 'REST', 'AIA-R1', 50, 'stub'),
    ('weaviate', 'data', 'REST,GraphQL', 'AIA-R1', 50, 'stub'),
    ('milvus', 'data', 'gRPC', 'AIA-R1', 50, 'stub'),
    ('qdrant', 'data', 'REST,gRPC', 'AIA-R1', 50, 'stub'),
    ('neo4j', 'data', 'Bolt', 'AIA-R1', 50, 'stub'),
    ('elasticsearch', 'data', 'REST', 'AIA-R1', 50, 'stub'),
    ('kafka', 'messaging', 'Kafka', 'AIA-R1', 50, 'stub'),
    ('nats', 'messaging', 'NATS', 'AIA-R0', 40, 'stub'),
    ('rabbitmq', 'messaging', 'AMQP', 'AIA-R0', 40, 'stub'),
    ('mqtt', 'messaging', 'MQTT', 'AIA-R0', 40, 'stub'),
    ('amqp', 'messaging', 'AMQP', 'AIA-R0', 40, 'stub'),
    ('pulsar', 'messaging', 'Pulsar', 'AIA-R0', 40, 'stub'),
    ('aws-sqs', 'messaging', 'REST', 'AIA-R1', 50, 'stub'),
    ('azure-servicebus', 'messaging', 'AMQP,REST', 'AIA-R1', 50, 'stub'),
    ('opcua', 'industrial', 'OPC-UA', 'AIA-R3', 70, 'stub'),
    ('modbus', 'industrial', 'Modbus', 'AIA-R3', 70, 'stub'),
    ('bacnet', 'industrial', 'BACnet', 'AIA-R3', 70, 'stub'),
    ('scada', 'industrial', 'OPC-UA,Custom', 'AIA-R3', 70, 'stub'),
    ('plc', 'industrial', 'Modbus,Custom', 'AIA-R3', 70, 'stub'),
    ('sparkplug', 'industrial', 'MQTT-Sparkplug', 'AIA-R3', 70, 'stub'),
    ('profinet', 'industrial', 'PROFINET', 'AIA-R3', 70, 'stub'),
    ('ethernet-ip', 'industrial', 'EtherNet/IP', 'AIA-R3', 70, 'stub'),
    ('aws-s3', 'cloud', 'REST', 'AIA-R1', 50, 'stub'),
    ('aws-lambda', 'cloud', 'REST', 'AIA-R1', 50, 'stub'),
    ('aws-eks', 'cloud', 'REST', 'AIA-R2', 60, 'stub'),
    ('azure-blob', 'cloud', 'REST', 'AIA-R1', 50, 'stub'),
    ('azure-aks', 'cloud', 'REST', 'AIA-R2', 60, 'stub'),
    ('azure-functions', 'cloud', 'REST', 'AIA-R1', 50, 'stub'),
    ('gcp-storage', 'cloud', 'REST', 'AIA-R1', 50, 'stub'),
    ('gcp-gke', 'cloud', 'REST', 'AIA-R2', 60, 'stub'),
    ('gcp-cloudrun', 'cloud', 'REST', 'AIA-R1', 50, 'stub'),
    ('cloudflare', 'cloud', 'REST', 'AIA-R1', 50, 'stub'),
    ('gov-digital-identity', 'government', 'REST,OIDC', 'AIA-R3', 70, 'stub'),
    ('gov-citizen-services', 'government', 'REST', 'AIA-R3', 70, 'stub'),
    ('gov-notify', 'government', 'REST', 'AIA-R2', 60, 'stub'),
    ('gov-pay', 'government', 'REST', 'AIA-R3', 70, 'stub'),
    ('moodle', 'education', 'REST', 'AIA-R2', 60, 'stub'),
    ('canvas', 'education', 'REST,GraphQL', 'AIA-R2', 60, 'stub'),
    ('blackboard', 'education', 'REST', 'AIA-R2', 60, 'stub'),
    ('google-classroom', 'education', 'REST', 'AIA-R2', 60, 'stub')
ON CONFLICT (name) DO NOTHING;
